export const GET_WALLETS_DATA = 'WALLET/GET_WALLETS_DATA'
export const GET_WALLETS_FETCH_ERROR = 'WALLET/GET_WALLETS_FETCH_ERROR'
export const GET_WALLETS_FETCH = 'WALLET/GET_WALLETS_FETCH'
export const RESET_WALLETS_ACCOUNT = 'RESET_WALLETS_ACCOUNT'
